name: Python searching_tweets.py

on: [push]

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.8
        
    - name: Install dependencies
      run: |
        make install
        
    - name: Lint with pylint
      run: |
        export access_key: ${{ secrets.ACCESS_KEY }}
        export secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
        export OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        export Credentials_Access_Key_ID: ${{ secrets.CREDENTIALS_ACCESS_KEY_ID }}
        export Credentials_Secret_Access_Key: ${{ secrets.CREDENTIALS_SECRET_ACCESS_KEY }}
        export  consumer_key: ${{ secrets.CONSUMER_KEY }}
        export consumer_secret: ${{ secrets.CONSUMER_SECRET }}
        export Bearer_Token: ${{ secrets.BEARER_TOKEN }}
        export Token: ${{ secrets.TOKEN }}
        export Token_Secret: ${{ secrets.TOKEN_SECRET }}
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
