name: Python main_old_coin.py

on:
  workflow_dispatch:
    
#   schedule:
#     - cron: '0 0 * * *'
    
jobs:   
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.8
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'

    - name: Install dependencies
      run: |
        make install
    
    - name: run python
      env:
       AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
       CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
       CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
       BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
       TOKEN: ${{ secrets.TOKEN }}
       TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
       
#         echo AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
#         echo AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY}}
#         echo CONSUMER_KEY: "${CONSUMER_KEY}"
#         echo CONSUMER_SECRET: "${CONSUMER_SECRET}"
#         echo BEARER_TOKEN: "${BEARER_TOKEN}"
#         echo TOKEN: "${TOKEN}"
#         echo TOKEN_SECRET: "${TOKEN_SECRET}"
       
      run: |
        python main_old_coin.py

    
    
