name: Python searching_tweets.py

on: [push]

jobs:   
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.8
      env:
       consumer_key: ${{ secrets.CONSUMER_KEY }}
       consumer_secret: ${{ secrets.CONSUMER_SECRET }}
       Bearer_Token: ${{ secrets.BEARER_TOKEN }}
       Token: ${{ secrets.TOKEN }}
       Token_Secret: ${{ secrets.TOKEN_SECRET }}

    - name: Set AWS credentials         
      uses: aws-actions/configure-aws-credentials@v1  
      with:           
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}           
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}           
#         aws-region: eu-west-1


    - name: Install dependencies
      run: |
        make install
    
    - name: run python
      env:
       consumer_key: ${{ secrets.CONSUMER_KEY }}
       consumer_secret: ${{ secrets.CONSUMER_SECRET }}
       Bearer_Token: ${{ secrets.BEARER_TOKEN }}
       Token: ${{ secrets.TOKEN }}
       Token_Secret: ${{ secrets.TOKEN_SECRET }}
      run: |
        echo consumer_key: "${CONSUMER_KEY}"
        echo consumer_secret: "${CONSUMER_SECRET}"
        echo Bearer_Token: "${BEARER_TOKEN}"
        echo Token: "${TOKEN}"
        echo Token_Secret: "${TOKEN_SECRET}"
        python searching_tweets.py

    
    
