name: Python searching_tweets.py

on: [push]

jobs:   
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.8
        
    - name: Install dependencies
      run: |
        make install
        
    - name: Lint with pylint
      env:
       access_key: ${{ secrets.ACCESS_KEY }}
       secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
       consumer_key: ${{ secrets.CONSUMER_KEY }}
       consumer_secret: ${{ secrets.CONSUMER_SECRET }}
       Bearer_Token: ${{ secrets.BEARER_TOKEN }}
       Token: ${{ secrets.TOKEN }}
       Token_Secret: ${{ secrets.TOKEN_SECRET }}
      run: |
        make lint
    - name: Test with pytest
      env:
       access_key: ${{ secrets.ACCESS_KEY }}
       secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
       consumer_key: ${{ secrets.CONSUMER_KEY }}
       consumer_secret: ${{ secrets.CONSUMER_SECRET }}
       Bearer_Token: ${{ secrets.BEARER_TOKEN }}
       Token: ${{ secrets.TOKEN }}
       Token_Secret: ${{ secrets.TOKEN_SECRET }}
       
      run: |
        make test
    - name: Format code
      run: |
        make format
