name: Python newsApp/News_df.py

on:
  workflow_dispatch:
    
  schedule:
    - cron: '* */4 * * *'
    
jobs:   
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.8
        args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'


    - name: Install dependencies
      run: |
        make install
  
    - name: run python
      env:
       aws-access-key-id: ${{ secrets.ACCESS_KEY }}
       aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
      run: |
        echo aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        echo aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY}}
        python newsApp/News_df.py
        
